import React, { useState } from 'react';
import {
  AlertTriangle,
  ShieldAlert,
  Sparkles,
  Filter,
  Layers,
  ArrowRight,
  FileText,
  Stethoscope,
  CheckCircle2,
  Copy,
  Info
} from 'lucide-react';
import { useMedication } from '../context/MedicationContext';
import { InteractionCard } from '../components/specific/InteractionCard';
import { DuplicateCard } from '../components/specific/DuplicateCard';
import { RiskBadge } from '../components/common/RiskBadge';
import { DisclaimerBanner } from '../components/layout/DisclaimerBanner';

export const InteractionResults = () => {
  const {
    interactions,
    duplicates,
    safetyStats,
    navigateTo,
    setSelectedInteractionId
  } = useMedication();

  const [activeTab, setActiveTab] = useState('ALL'); // 'ALL' | 'HIGH' | 'MODERATE' | 'LOW' | 'DUPLICATES' | 'SAFE'

  const highInteractions = interactions.filter(i => i.severity === 'HIGH');
  const modInteractions = interactions.filter(i => i.severity === 'MODERATE');
  const lowInteractions = interactions.filter(i => i.severity === 'LOW');

  const filteredInteractions = interactions.filter(i => {
    if (activeTab === 'ALL') return true;
    if (activeTab === 'HIGH') return i.severity === 'HIGH';
    if (activeTab === 'MODERATE') return i.severity === 'MODERATE';
    if (activeTab === 'LOW') return i.severity === 'LOW';
    return false;
  });

  return (
    <div className="space-y-8 animate-fade-in max-w-6xl mx-auto">
      {/* Top Header Strip */}
      <div className="flex flex-col sm:flex-row items-start sm:items-center justify-between gap-4">
        <div>
          <div className="inline-flex items-center gap-1.5 px-3 py-1 rounded-full bg-cyan-50 dark:bg-cyan-950/50 border border-cyan-200 dark:border-cyan-800 text-cyan-700 dark:text-cyan-300 text-xs font-bold mb-2">
            <Sparkles className="w-3.5 h-3.5" /> Clinical Safety Engine Results
          </div>
          <h1 className="text-3xl font-extrabold text-slate-900 dark:text-white font-display">
            Medication Safety Analysis
          </h1>
          <p className="text-sm text-slate-700 dark:text-slate-200 mt-1">
            Complete interaction and duplication audit generated by cross-referencing all active prescriptions.
          </p>
        </div>

        <div className="flex items-center gap-3">
          <button
            onClick={() => navigateTo('patient-report')}
            className="px-4 py-2.5 rounded-xl bg-slate-100 dark:bg-slate-800 hover:bg-slate-200 dark:hover:bg-slate-700 text-xs font-bold text-slate-800 dark:text-slate-200 transition-colors flex items-center gap-1.5"
          >
            <FileText className="w-4 h-4 text-cyan-600" />
            <span>Patient Report</span>
          </button>

          <button
            onClick={() => navigateTo('doctor-report')}
            className="px-4 py-2.5 rounded-xl bg-gradient-to-r from-indigo-600 to-purple-600 hover:from-indigo-500 hover:to-purple-500 text-white text-xs font-bold shadow-md hover:shadow-lg transition-all flex items-center gap-1.5"
          >
            <Stethoscope className="w-4 h-4" />
            <span>Doctor Clinical Report</span>
          </button>
        </div>
      </div>

      {/* Summary Metrics Bar (Section 10 Requirement) */}
      <div className="grid grid-cols-2 sm:grid-cols-3 lg:grid-cols-5 gap-4 p-6 rounded-3xl bg-slate-900 text-white border border-slate-800 shadow-elevated">
        <div className="space-y-1">
          <span className="text-[11px] font-bold uppercase tracking-wider text-slate-400">
            Total Regimen
          </span>
          <p className="text-2xl font-bold font-display text-white">
            {safetyStats.totalMedicines} Medicines
          </p>
          <p className="text-[11px] text-slate-400">4 Prescriptions</p>
        </div>

        <div className="space-y-1 border-l border-slate-800 pl-4">
          <span className="text-[11px] font-bold uppercase tracking-wider text-slate-400">
            Combinations
          </span>
          <p className="text-2xl font-bold font-display text-cyan-400">
            {safetyStats.combinationsChecked} Checked
          </p>
          <p className="text-[11px] text-slate-400">N*(N-1)/2 matrix</p>
        </div>

        <div className="space-y-1 border-l border-slate-800 pl-4">
          <span className="text-[11px] font-bold uppercase tracking-wider text-slate-400">
            Interactions
          </span>
          <p className="text-2xl font-bold font-display text-amber-400">
            {safetyStats.activeInteractions} Flagged
          </p>
          <p className="text-[11px] text-slate-400">Drug-drug pairs</p>
        </div>

        <div className="space-y-1 border-l border-slate-800 pl-4">
          <span className="text-[11px] font-bold uppercase tracking-wider text-slate-400">
            Duplicates
          </span>
          <p className="text-2xl font-bold font-display text-purple-400">
            {safetyStats.duplicateMedicines} Cross-Rx
          </p>
          <p className="text-[11px] text-slate-400">Same ingredient</p>
        </div>

        <div className="space-y-1 border-l border-slate-800 pl-4 col-span-2 sm:col-span-1">
          <span className="text-[11px] font-bold uppercase tracking-wider text-slate-400">
            High-Risk Alert
          </span>
          <p className="text-2xl font-bold font-display text-red-400">
            {safetyStats.highRiskAlerts} Urgent
          </p>
          <p className="text-[11px] text-red-300">Action Required</p>
        </div>
      </div>

      {/* Filter Tabs by Severity Category (Section 10 Requirement) */}
      <div className="flex items-center gap-2 overflow-x-auto pb-2">
        <button
          onClick={() => setActiveTab('ALL')}
          className={`px-4 py-2 rounded-xl text-xs font-bold transition-all ${
            activeTab === 'ALL'
              ? 'bg-slate-900 dark:bg-white text-white dark:text-slate-900 shadow-sm'
              : 'bg-white dark:bg-slate-900 border border-slate-200 dark:border-slate-800 text-slate-600 dark:text-slate-300'
          }`}
        >
          All Findings ({interactions.length + (duplicates.length > 0 ? 1 : 0)})
        </button>

        <button
          onClick={() => setActiveTab('HIGH')}
          className={`px-4 py-2 rounded-xl text-xs font-bold transition-all flex items-center gap-1.5 ${
            activeTab === 'HIGH'
              ? 'bg-red-600 text-white shadow-sm'
              : 'bg-white dark:bg-slate-900 border border-slate-200 dark:border-slate-800 text-red-600 hover:bg-red-50'
          }`}
        >
          <span className="w-2 h-2 rounded-full bg-red-500" />
          <span>High Risk ({highInteractions.length})</span>
        </button>

        <button
          onClick={() => setActiveTab('MODERATE')}
          className={`px-4 py-2 rounded-xl text-xs font-bold transition-all flex items-center gap-1.5 ${
            activeTab === 'MODERATE'
              ? 'bg-amber-600 text-white shadow-sm'
              : 'bg-white dark:bg-slate-900 border border-slate-200 dark:border-slate-800 text-amber-600 hover:bg-amber-50'
          }`}
        >
          <span className="w-2 h-2 rounded-full bg-amber-500" />
          <span>Moderate Risk ({modInteractions.length})</span>
        </button>

        <button
          onClick={() => setActiveTab('LOW')}
          className={`px-4 py-2 rounded-xl text-xs font-bold transition-all flex items-center gap-1.5 ${
            activeTab === 'LOW'
              ? 'bg-cyan-600 text-white shadow-sm'
              : 'bg-white dark:bg-slate-900 border border-slate-200 dark:border-slate-800 text-cyan-600 hover:bg-cyan-50'
          }`}
        >
          <span className="w-2 h-2 rounded-full bg-cyan-500" />
          <span>Low Risk ({lowInteractions.length})</span>
        </button>

        <button
          onClick={() => setActiveTab('DUPLICATES')}
          className={`px-4 py-2 rounded-xl text-xs font-bold transition-all flex items-center gap-1.5 ${
            activeTab === 'DUPLICATES'
              ? 'bg-purple-600 text-white shadow-sm'
              : 'bg-white dark:bg-slate-900 border border-slate-200 dark:border-slate-800 text-purple-600 hover:bg-purple-50'
          }`}
        >
          <span className="w-2 h-2 rounded-full bg-purple-500" />
          <span>Duplicate Medicines ({duplicates.length})</span>
        </button>
      </div>

      {/* Results Feed */}
      <div className="space-y-6">
        {/* Render Duplicates if tab is ALL or DUPLICATES */}
        {(activeTab === 'ALL' || activeTab === 'DUPLICATES') && duplicates.length > 0 && (
          <div className="space-y-4">
            <div className="flex items-center gap-2">
              <Copy className="w-4 h-4 text-purple-600" />
              <h3 className="text-base font-bold text-slate-900 dark:text-white font-display">
                Cross-Prescription Duplicate Active Ingredients
              </h3>
            </div>
            {duplicates.map((dup) => (
              <DuplicateCard key={dup.id} duplicate={dup} />
            ))}
          </div>
        )}

        {/* Render Interactions */}
        {activeTab !== 'DUPLICATES' && (
          <div className="space-y-6">
            {filteredInteractions.map((interaction) => (
              <InteractionCard
                key={interaction.id}
                interaction={interaction}
                onDetailsClick={() => {
                  setSelectedInteractionId(interaction.id);
                  navigateTo('detailed-interaction', { interactionId: interaction.id });
                }}
              />
            ))}
          </div>
        )}

        {/* No items in current filter state */}
        {filteredInteractions.length === 0 && activeTab !== 'DUPLICATES' && (
          <div className="p-12 text-center rounded-3xl border border-slate-200 dark:border-slate-800 bg-white dark:bg-slate-900">
            <CheckCircle2 className="w-12 h-12 text-emerald-500 mx-auto mb-3" />
            <h3 className="text-lg font-bold text-slate-900 dark:text-white">No interactions found in this category</h3>
            <p className="text-xs text-slate-700 dark:text-slate-200 mt-1">All other combinations are cleared as safe.</p>
          </div>
        )}
      </div>

      {/* Mandatory Medical Safety Notice (Section 10 & 22 Requirement) */}
      <DisclaimerBanner />
    </div>
  );
};
